-- ORMA_PROFESIONALS

CREATE SEQUENCE SEQU_ORMA_PROFESIONALS;

CREATE TABLE ORMA_PROFESSIONALS (
	PROF_ID INTEGER DEFAULT (NEXT VALUE FOR SEQU_ORMA_PROFESIONALS) NOT NULL AUTO_INCREMENT,
	PROF_NAME VARCHAR(50) NOT NULL,
	PROF_SURNAME_1 VARCHAR(50),
	PROF_SURNAME_2 VARCHAR(50),
	PROF_ID_VALUE VARCHAR(100) NOT NULL,
	PROF_DELETED BOOLEAN NOT NULL,
    PROF_DELETED_DATE TIMESTAMP,
	CONSTRAINT PK_PROFESSIONALS PRIMARY KEY (PROF_ID)
);
CREATE UNIQUE INDEX IDX_PK_OP_PROF_ID ON ORMA_PROFESSIONALS (PROF_ID);

-- ORMA_CENTERS

CREATE SEQUENCE SEQU_ORMA_CENTERS;

CREATE TABLE ORMA_CENTERS (
	CENT_ID INTEGER DEFAULT (NEXT VALUE FOR SEQU_ORMA_CENTERS) NOT NULL AUTO_INCREMENT,
	CENT_CODE VARCHAR(50) NOT NULL,
	CENT_NAME VARCHAR(50),
	CENT_DELETED BOOLEAN NOT NULL,
	CENT_DELETED_DATE TIMESTAMP NULL,
	CONSTRAINT PK_CENT PRIMARY KEY (CENT_ID)
);
CREATE UNIQUE INDEX IDX_PK_OC_CENT_ID ON ORMA_CENTERS (CENT_ID);

-- ORMA_SERVICES

CREATE SEQUENCE SEQU_ORMA_SERVICE;

CREATE TABLE ORMA_SERVICES (
	SERV_ID INTEGER DEFAULT (NEXT VALUE FOR SEQU_ORMA_SERVICE) NOT NULL AUTO_INCREMENT,
	SERV_CODE VARCHAR(50) NOT NULL,
	SERV_DESCRIPTION VARCHAR(50),
	SERV_DELETED BOOLEAN NOT NULL,
	SERV_DELETED_DATE TIMESTAMP NULL,
	CONSTRAINT PK_SERV PRIMARY KEY (SERV_ID)
);
CREATE UNIQUE INDEX IDX_PK_OS_SERV_ID ON ORMA_SERVICES (SERV_ID);

-- ORMA_AMBITS

CREATE SEQUENCE SEQU_ORMA_AMBITS;

CREATE TABLE ORMA_AMBITS (
	AMBI_ID INTEGER DEFAULT (NEXT VALUE FOR SEQU_ORMA_AMBITS) NOT NULL AUTO_INCREMENT,
	AMBI_CODE VARCHAR(50) NOT NULL,
	AMBI_DESCRIPTION VARCHAR(50),
	AMBI_DELETED BOOLEAN NOT NULL,
	AMBI_DELETED_DATE TIMESTAMP NULL,
	CONSTRAINT PK_AMBI PRIMARY KEY (AMBI_ID)
);
CREATE UNIQUE INDEX IDX_PK_OS_AMBI_ID ON ORMA_AMBITS (AMBI_ID);

-- SECU_USERS

CREATE SEQUENCE SEQU_SECU_USERS;

CREATE TABLE SECU_USERS (
	USER_ID INTEGER DEFAULT (NEXT VALUE FOR SEQU_SECU_USERS) NOT NULL AUTO_INCREMENT,
	PROF_ID INTEGER NOT NULL,
	USER_LOGIN VARCHAR(100) NOT NULL,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY (USER_ID),
	CONSTRAINT FK_USER FOREIGN KEY (PROF_ID) REFERENCES ORMA_PROFESSIONALS(PROF_ID)
);
CREATE UNIQUE INDEX IDX_PK_SU_USER_ID ON SECU_USERS (USER_ID);
CREATE INDEX IDX_FK_SU_PROF_ID ON SECU_USERS (PROF_ID);

-- SECU_ROLES

CREATE SEQUENCE SEQU_SECU_ROLES;

CREATE TABLE SECU_ROLES (
	SROL_ID INTEGER DEFAULT (NEXT VALUE FOR SEQU_SECU_ROLES) NOT NULL AUTO_INCREMENT,
	SROL_CODE VARCHAR(50) NOT NULL,
	SROL_DESCRIPTION VARCHAR(50),
	SROL_DELETED BOOLEAN NOT NULL,
	SROL_DELETED_DATE TIMESTAMP NULL,
	CONSTRAINT PK_SROL PRIMARY KEY (SROL_ID)
);
CREATE UNIQUE INDEX IDX_PK_SR_SROL_ID ON SECU_ROLES (SROL_ID);



