-- CONF_ACTIONS

INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATIONS_GET', 'Consultar información estaciones de trabajo', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_ADMIN', 'Acceso a estación administrativa', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_HOSP', 'Acceso a estación hospitalización', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_URG', 'Acceso a estación urgencias', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_CCEE', 'Acceso a estación consultas externas', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_RADIO', 'Acceso a estación radiología', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_LAB', 'Acceso a estación laboratorio', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_SCHEDULES', 'Acceso a estación agendas', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_ADMISSION_URG', 'Acceso a estación admisión urgencias', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_EMERGENCY', 'Acceso a estación ambulancias', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_CRUD', 'Acceso a estación CRUD', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_CONF_FORMS', 'Acceso a estación configuración formularios', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_MORGUE', 'Acceso a estación morgue', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_PRIMARY_HEALTHCARE', 'Acceso a estación primeros cuidados', 1, '2017-10-31 17:41:50.877');
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_PHYSIOTHERAPY', 'Acceso a estación fisioterapia', 1, '2017-10-31 17:41:50.877');
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_ADMISSION_HOSP', 'Acceso a estación admisión hospitalización', 1, '2017-10-31 17:41:50.877');
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_RADIO_ASIGN', 'Asignar radiológo', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_CONF_MENUS', 'Acceso a estación configuración de menus', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_NURSING_URG', 'Acceso a estación enfermeria de urgencias', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_OUTPATIENT_ADMISSION', 'Admisión CCEE', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_PHARMACIE', 'Farmacia', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES( 'ROLE_STATION_INPATIENT_ADMISSION', 'Adm. Hospitalización', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_PREVENTIVE_MEDICINE', 'Medicina Preventiva', 0, NULL);
INSERT INTO CONF_ACTIONS
(SIAC_NAME, SIAC_DESCRIPTION, SIAC_DELETED, SIAC_DELETED_DATE)
VALUES('ROLE_STATION_PPQT', 'Planificador quirúrgico', 0, NULL);

-- CONF_STATION_STRUCTURES

INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(2, 'Administración', 'Clic aquí para acceder al módulo de administración', 'ADMIN');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(3, 'Hospitalización', 'Clic aquí para acceder al módulo de hospitalización', 'HOSPI');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(4, 'Urgencias', 'Clic aquí para acceder al módulo de urgencias', 'EMER');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(6, 'Radiología', 'Clic aquí para acceder al módulo de radiología', 'RADIO');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(7, 'Laboratorio', 'Clic aquí para acceder al módulo de laboratorio', 'LABO');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(8, 'Agendas y Citación', 'Clic aquí para acceder al módulo de agendas y citación', 'SCHE');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(9, 'Adm. Urgencias', 'Clic aquí para acceder al módulo de admisión de urgencias', 'EMERADM');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(10, 'Adm. Ambulancias', 'Clic aquí para acceder al módulo de admisión de ambulancias', 'AMBUADM');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(11, 'Mant. de Datos', 'Clic aquí para acceder al módulo de mantenimiento de datos', 'DATA');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(12, 'Conf. de Formularios', 'Clic aquí para acceder al módulo de configuración de formularios', 'FORMS');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(13, 'Morgue', 'Clic aquí para acceder al módulo de planificación de morgue', 'MORG');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(5, 'Consultas Externas', 'Clic aquí para acceder al módulo de CCEE', 'CCEE');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(20, 'Adm. Consultas Externas', 'Clic aquí para acceder al módulo de Admisión de CCEE', 'CCEEADM');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(21, 'Farmacia', 'Clic aquí para acceder al módulo de Farmacia', 'PHARM');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(22, 'Adm. Hospitalización', 'Clic aquí para acceder al módulo de admisión de hospitalización', 'HOSPIADM');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(24, 'Plan. Quirófanos', 'Clic aquí para acceder al módulo de planificación de quirófanos', 'OPERPLAN');
INSERT INTO CONF_STATION_STRUCTURES
(SIAC_ID, CSTS_DESCRIPTION, CSTS_LONG_DESCRIPTION, CSTS_CODE)
VALUES(23, 'Medicina Preventiva', 'Clic aquí para acceder al módulo de CCEE', 'PREVMED');