-- ORMA_PROFESIONALS

INSERT INTO ORMA_PROFESSIONALS
(PROF_NAME, PROF_SURNAME_1, PROF_SURNAME_2, PROF_ID_VALUE, PROF_DELETED, PROF_DELETED_DATE)
VALUES('Araceli', 'Bernal', 'Velasco', '74516878Y', 0, NULL);

INSERT INTO ORMA_PROFESSIONALS
(PROF_NAME, PROF_SURNAME_1, PROF_SURNAME_2, PROF_ID_VALUE, PROF_DELETED, PROF_DELETED_DATE)
VALUES('Miguel Ángel', 'Armenteros', 'Pérez', '77343191X', 0, NULL);

INSERT INTO ORMA_PROFESSIONALS
(PROF_NAME, PROF_SURNAME_1, PROF_SURNAME_2, PROF_ID_VALUE, PROF_DELETED, PROF_DELETED_DATE)
VALUES('Eva', 'Fuentes', 'Martinez', 'DEFECTO16', 0, NULL);

-- ORMA_CENTERS

INSERT INTO ORMA_CENTERS
(CENT_CODE, CENT_NAME, CENT_DELETED, CENT_DELETED_DATE)
VALUES('H001', 'HOSPITAL CLINICA BENIDORM', 0, NULL);
INSERT INTO ORMA_CENTERS
(CENT_CODE, CENT_NAME, CENT_DELETED, CENT_DELETED_DATE)
VALUES('H002', 'HOSPITAL DENIA ', 0, NULL);
INSERT INTO ORMA_CENTERS
(CENT_CODE, CENT_NAME, CENT_DELETED, CENT_DELETED_DATE)
VALUES('P001', 'POLICLINICA CLINICA BENIDORM', 0, NULL);
INSERT INTO ORMA_CENTERS
(CENT_CODE, CENT_NAME, CENT_DELETED, CENT_DELETED_DATE)
VALUES('P002', 'BEANACA', 0, NULL);
INSERT INTO ORMA_CENTERS
(CENT_CODE, CENT_NAME, CENT_DELETED, CENT_DELETED_DATE)
VALUES('P003', 'CENTRO SALUS ALBIR', 0, NULL);
INSERT INTO ORMA_CENTERS
(CENT_CODE, CENT_NAME, CENT_DELETED, CENT_DELETED_DATE)
VALUES('P004', 'CENTRO POLICLINICO CALPE', 0, NULL);

-- ORMA_SERVICES

INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('03', 'ALERGOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('05', 'ANATOMIA PATOLOGICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('06', 'ANESTESIOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('07', 'ANGIOLOGIA Y CIR. VASCULAR', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('58', 'APARATO DIGESTIVO', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('09', 'CARDIOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('10', 'CIRUGIA CARDIOVASCULAR', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('11', 'CIRUGIA GENERAL Y DEL APARATO DIGESTIVO', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('12', 'CIRUGIA MAXILOFACIAL', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('13', 'CIRUGIA PEDIATRICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('14', 'CIRUGIA PLASTICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('15', 'CIRUGIA TORACICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('16', 'DERMATOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('18', 'ENDOCRINOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('20', 'GERIATRIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('21', 'HEMATOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('51', 'HEMODINAMICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('22', 'INMUNOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('01', 'MEDICINA GENERAL', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('23', 'MEDICINA INTENSIVA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('24', 'MEDICINA INTERNA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('25', 'MEDICINA NUCLEAR', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('26', 'NEFROLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('27', 'NEUMOLOGÍA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('28', 'NEUROCIRUGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('29', 'NEUROFISIOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('30', 'NEUROLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('31', 'OBSTETRICIA Y GINECOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('55', 'ODONTOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('32', 'OFTALMOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('33', 'ONCOLOGIA MEDICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('34', 'ONCOLOGIA RADIOTERAPICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('ORL', 'ORL', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('02', 'PEDIATRIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('36', 'PSIQUIATRIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('52', 'RADIOINTERVENCIONISMO', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('54', 'RADIOINTERVENCIONISMO VASCULAR', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('17', 'RADIOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('37', 'REHABILITACION', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('38', 'REUMATOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('39', 'TRATAMIENTO DEL DOLOR', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('40', 'TRAUMATOLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('50', 'UNIDAD ARRITMIAS Y ELECTROFISIOLOGIA ', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('53', 'URGENCIAS', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('41', 'UROLOGIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('04', 'ANALISIS CLINICOS', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('103', 'ADMINISTRADORES', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('00', 'ENFERMERÍA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('57', 'PODOLOGÍA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('56', 'PSICOLOGÍA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('59', 'CIRUGIA BARIATRICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('AB', 'AMBULACIAS', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('FA', 'FARMACIA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('HZ', 'HOSPITALIZACIÓN', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('QX', 'QUIRÓFANO', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('REC', 'ADMISION - RECEPCIÓN', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('CIT', 'ADMISION - CITACIÓN', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('PRE', 'Prevención', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('ASI', 'ASITENCIAL', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('BMM', 'BIOMECÁNICA DE LA MARCHA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('PSC', 'PSICOLOGÍA CLÍNICA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('PSD', 'PSICOLOGÍA DEPORTIVA', 0, NULL);
INSERT INTO ORMA_SERVICES
(SERV_CODE, SERV_DESCRIPTION, SERV_DELETED, SERV_DELETED_DATE)
VALUES('UHD', 'UHD', 0, NULL);

-- ORMA_AMBITS

INSERT INTO ORMA_AMBITS
(AMBI_CODE,AMBI_DESCRIPTION,AMBI_DELETED,AMBI_DELETED_DATE)
VALUES ('H','Hospitalización',0,NULL);
INSERT INTO ORMA_AMBITS
(AMBI_CODE,AMBI_DESCRIPTION,AMBI_DELETED,AMBI_DELETED_DATE)
VALUES ('C','Consultas Externas',0,NULL);
INSERT INTO ORMA_AMBITS
(AMBI_CODE,AMBI_DESCRIPTION,AMBI_DELETED,AMBI_DELETED_DATE)
VALUES ('U','Urgencias',0,NULL);
INSERT INTO ORMA_AMBITS
(AMBI_CODE,AMBI_DESCRIPTION,AMBI_DELETED,AMBI_DELETED_DATE)
VALUES ('A','Administracion',0,NULL);
INSERT INTO ORMA_AMBITS
(AMBI_CODE,AMBI_DESCRIPTION,AMBI_DELETED,AMBI_DELETED_DATE)
VALUES ('M','Hospitalización Domiciliaria',0,NULL);
