SELECT
	op.PROF_NAME,
	op.PROF_SURNAME_1,
	op.PROF_SURNAME_2,
	sr.SROL_DESCRIPTION,
	oc.CENT_NAME,
	os.SERV_DESCRIPTION,
	oa.AMBI_DESCRIPTION
FROM
	ORMA_PROFESSIONALS op
INNER JOIN SECU_PROFESSIONAL_ROLES spr ON
	op.PROF_ID = spr.PROF_ID
INNER JOIN SECU_CONFIG_ROLES scr ON
	spr.SCRO_ID = scr.SCRO_ID
INNER JOIN SECU_ROLES sr ON
	scr.SROL_ID = sr.SROL_ID
INNER JOIN ORMA_CENTERS oc ON
	scr.CENT_ID = oc.CENT_ID
INNER JOIN ORMA_SERVICES os ON
	scr.SERV_ID = os.SERV_ID
INNER JOIN ORMA_AMBITS oa ON
	scr.AMBI_ID = oa.AMBI_ID
WHERE
	PROF_NAME = 'Araceli'