SELECT
	css.CSTS_DESCRIPTION,
	css.CSTS_LONG_DESCRIPTION
FROM
	SECU_USERS su
INNER JOIN SECU_PROFESSIONAL_ROLES spr ON
	su.PROF_ID = spr.PROF_ID
INNER JOIN SECU_PROF_ROLE_ACTIONS spra ON
	spra.SCRO_ID = spr.SCRO_ID
INNER JOIN CONF_STATION_STRUCTURES css ON
	css.SIAC_ID = spra.SIAC_ID
WHERE
	spr.USRO_FAVOURITE = TRUE
	AND su.USER_LOGIN LIKE 'abernal'